### PR TITLE
add firestore database; fix some typo;

### PR DESCRIPTION
**Pull request by haidarrifki**
#2 add firestore database for chat message & fix some typo on file index.html

### CODE REVIEW

**Comment by thesauravkarmakar** [comment]
> #2

Write Proper PR Summary

**Comment by haidarrifki** [comment]
> > #2
> 
> Write Proper PR Summary

sorry, updated

**Comment by thesauravkarmakar** [comment]
> > > #2
> > 
> > 
> > Write Proper PR Summary
> 
> ok, updated

Give some-time, within 24-48 hours we will go through it and if there are no issues. It will be merged.

**Comment by haidarrifki** [comment]
> > > > #2
> > > 
> > > 
> > > Write Proper PR Summary
> > 
> > 
> > ok, updated
> 
> Give some-time, within 24-48 hours we will go through it and if there are no issues. It will be merged.

okay, thanks!

**Comment by thesauravkarmakar** [comment]
> #2 add firestore database for chat message & fix some typo on file index.html

Write a proper README for setting up Firebase Database if you can.

**Comment by haidarrifki** [comment]
> > #2 add firestore database for chat message & fix some typo on file index.html
> 
> Write a proper README for setting up Firebase Database if you can.

for setting up firestore database i follow the instruction here https://www.npmjs.com/package/firebase

sorry, but what i must supposed to write on README?

**Comment by thesauravkarmakar** [comment]
> > > #2 add firestore database for chat message & fix some typo on file index.html
> > 
> > 
> > Write a proper README for setting up Firebase Database if you can.
> 
> for setting up firestore database i follow the instruction here https://www.npmjs.com/package/firebase
> 
> sorry, but what i must supposed to write on README?

Not in the README. Create another Step-by-Step instruction README for setting up Firebase Database.

**Comment by haidarrifki** [comment]
> Not in the README. Create another Step-by-Step instruction README for setting up Firebase Database.

i just added the README file in folder utils, is that ok?
btw sorry for my bad english, you can improve it if the instruction isn't clear enough 😄

**Comment by thesauravkarmakar** [comment]
@haidarrifki It's not able to store the chats. Please fix that! 

Change the Firebase Config, and if possible attach a photo or video demo of working.

**Comment by haidarrifki** [comment]
@thesauravkarmakar i changed firebase config with my credential and it can store the chats, here is the demo video
https://www.loom.com/share/adad102d2de441bc893c217e9414ff51

i think maybe there is something miss in your firebase config rules

**Pull request merged**
